{
    "apps": [
        {
            "arch": "armng", 
            "build_date": "2024-10-28_08:19:51", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "017c917f72805b2bd59528e4b5edcbab", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_11:14:14", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "09b5443e9866de390d5c3a0a4f1bbbd4", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_11:02:50", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "dac8a88d69e349e946b4588afa436a26", 
            "name": "node", 
            "tar_url": "node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_10:36:06", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "5e3eb16c559bb665e4967f119bcea15d", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_07:39:46", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "04644d4c4d93ea227776adc3ef1a7311", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_09:15:08", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "Module_softether.asp", 
            "md5": "94c07c416845bc68b749706ace3505db", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_09:16:56", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "a5e332a10b71ac28a06befe58974eda3", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-25_23:03:20", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "06b9ac9028c404d299e1c961d2a15ebd", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-28_22:28:51", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "6c11e66c708cebe76f85aa40ce9c42f7", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_10:31:23", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "8f15139f471d9526b568ddbd4609b63e", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_09:19:04", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "8860868fbefb190e4b28c56400f5745d", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_11:38:48", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "18388e7719f0fc618b6aba39db16df16", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_11:16:26", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "84a21a4b0ed4aa327c7d5d8944585dc2", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_11:06:46", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "bc03c66fd6f5771af7c31e7fd4a035cd", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_12:55:30", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "c47e14983324c20ebf46528c6ed6d138", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_08:56:09", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "01237df5f1cf21f96b203bd9df2492ce", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-28_08:36:34", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "ac4b9f3d6c4ac34c0a2352453f4e9832", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_15:08:48", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "b1633d925aa643656096947427cfd1cd", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-25_08:51:02", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "07e15c91244c69410524009c16c5ba52", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_11:10:25", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "6ce8d08a5dd98eb050b879580ffcd99d", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_07:34:50", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "b87d53bd9267c04c0787624318e3f06c", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-26_16:21:06", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "0d3bd888934457f05a0444755759c421", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_07:46:28", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "d173583c567a7b76ead83561de25936c", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_07:44:10", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "68bdc6cf26c1fb393a1cb443e762d162", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "build_date": "2020-08-20_11:41:38", 
            "description": "迅雷快鸟，为上网加速而生~", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "8eab08dedc59d3f80fb7468be744ae30", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "讯雷快鸟", 
            "version": "1.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_11:07:20", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "428f835ed3a4218003f5fb2b4017fe6f", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_10:59:48", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "eef491ebdcfe5e32d237886d31269dcd", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_19:13:41", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "2daddd392b8f779a6f5b44392ddd3d69", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_11:44:42", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "2bb644f5c6a289270023aa44bffef00a", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_10:39:02", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "395096d19773c5b52ed731f6a3a748f5", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_23:03:06", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "3348e0f70bdab8eca0d4fcac31c45f60", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-29_23:00:56", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "8270e08f50d95db391523796c14d1cec", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-25_09:04:50", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "5c024a2910fdabc03c995c12673b152f", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_10:22:37", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "b50eeb04dd9d6c1904801b0e7d596bb2", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-24_11:39:00", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "5155652c6c30047ff96ce15276b218f8", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-25_23:08:34", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "c2228919228cb912207ca9a851e48f08", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-30_11:01:45", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "11647c4460729a08d9a4418459967b17", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/paldier/softcenterarmng/master", 
    "md5": "e3ebd1bfaa82d0bbe2838064c8ecec76", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.3"
}